Fix PII edge case where neither Next Challenge nor Previous Challenge buttons are needed
uccser/cs-unplugged pull request #1452
Opened 2020-10-04 22:46 UTC by eAlasdair

If there is only one challenge, previously the 'Next challenge' would be hidden, but not the 'Previous challenge' one.

Now both are properly hidden

2020-10-04 23:44 UTC, courtneycb approved these changes

2020-10-05 00:29 UTC, eAlasdair commented
Accidentally fixed a different bug in this branch:

Fixes bug where if no translation is available, the challenge attempt page would be blank:
![image](https://user-images.githubusercontent.com/25916475/95030789-8eb38b80-070e-11eb-95d0-26d5fdc2f57d.png)

- Adds 'homepage' variable to the generic translation error template
- Directs user either to the homepage (PII home) or the topic page (Challenge page)

2020-10-05 01:00 UTC, courtneycb requested changes
Nice :+1:

2020-10-05 23:37 UTC, courtneycb approved these changes

2020-10-06 01:21 UTC, merged